name: Python application test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Flask Flask-Testing coverage yfinance

    - name: Run tests
      run: |
        coverage run -m unittest discover -s tests -p 'test_*.py'
    
    - name: Generate coverage report
      run: coverage report
